[metadata]
name = completeme
description = ToF dense reconstruction from sparse CMR
platforms = unix, linux, osx, cygwin, win32
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.11

[options]
packages =
    completeme
install_requires = file: requirements.txt
python_requires = >=3.11
package_dir =
    =src
zip_safe = no

[options.package_data]
completeme = py.typed

[flake8]
max-line-length = 160